[distillation]
maxmemory="64G"
threshold=1e-9
cuda=true
type="regression"
precompute_teacher=true
save_intermediate=false

[distillation.parameters]
epochs=10
optimizer="adadelta"
rho=0.95
loss="MSE"

[distillation.data]
format="taxinet"
batchsize=64
presized=false
path="./data/taxinet/32x16.h5"

[distillation.teacher]
framework="onnx"
input_shape=[1, 1, 16, 32]
input_format="NCHW"
model="./configs/networks/taxinet_32x16.onnx"

[distillation.data.transform.teacher]
grayscale=true
height=16
width=32
max_value=1

[distillation.data.transform.student]
grayscale=true
height=16
width=32
max_value=1

[distillation.data.train]
shuffle=true

[distillation.data.validation]
shuffle=false
