name = 'CIFAR'

[dnn]
	artifact = 'CIFAR10'
	onnx = 'configs/CCB.onnx'
	r4v_config = 'configs/CCB.r4v'

[ca]
	strength = 3

	[ca.parameters]
		[ca.parameters.level]
			neu = 3
			conv = 5
			prop = 5

		[ca.parameters.range]
			neu = ['1/3', '1']
			conv = ['1/5', '1']
			prop = [0, 4]

[evolutionary]
	explore_iterations = 10
	refine_iterations = 1
	refine_arity = 2

	inflation_rate = 2
	deflation_rate = 0.5

	parameters = ['neu', 'conv']
	parameters_lower_bounds = {'conv'='1/5', 'neu'='1/3'}
	parameters_upper_bounds = {'conv'='16', 'neu'='16'}


[train]
	epochs = 10
	drop_scheme = 'random'
	add_scheme = 'last_same_relu'

	[train.dispatch]
		platform = "local"


[verify]
	eps = 0.00392156863 #1/255
	#eps = 0.00784313725 #2/255

	time = 600
	memory = '128G'

	[verify.verifiers]
		SwarmHost = ['abcrown22']

	[verify.dispatch]
		platform = "local"