name = 'MNIST'

[dnn]
	artifact = 'MNIST'
	onnx = 'configs/M3x1024.onnx'
	r4v_config = 'configs/M3x1024.r4v'

[ca]
	strength = 3
	[ca.parameters]
		[ca.parameters.level]
			neu = 3
			fc = 3
			prop = 5

		[ca.parameters.range]
			neu = ['1/3', '1']
			fc = ['1/3', '1']
			prop = [0, 4]

[evolutionary]
	explore_iterations = 10
	refine_iterations = 1
	refine_arity = 2

	inflation_rate = 2
	deflation_rate = 0.5

	parameters = ['neu', 'fc']
	parameters_lower_bounds = {'fc'='1/3', 'neu'='1/3'}
	parameters_upper_bounds = {'fc'='128/3', 'neu'='24'}


[train]
	epochs = 10
	drop_scheme = 'random'
	add_scheme = 'last_same_relu'

	[train.dispatch]
		platform = "local"


[verify]
	eps = 0.02
	time = 600
	memory = '16G'

	[verify.verifiers]
		DNNV = ['marabou']

	[verify.dispatch]
		platform = "local"