name = 'REevo_cifar_neurify'

[dnn]
	artifact = 'CIFAR10'
	onnx = './configs/networks/cifar_conv_big.onnx'
	r4v_config = './configs/networks/cifar_conv_big.toml'
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 0

[ca]
	strength = 3

	[ca.parameters]
		[ca.parameters.level]
			neu = 3
			lay = 3
			prop = 5

		[ca.parameters.range]
			neu = ['1/3', '1']
			lay = ['4/6', '1']
			prop = [0, 4]



[evolutionary]
	iterations = 10
	arity = 2
	inflation_rate = 2
	deflation_rate = 0.5

	parameters = ['neu', 'fc']
	parameters_upper_bounds = {'fc'='128/3', 'neu'='24'}

[train]
	epochs = 10
	drop_scheme = 'order'
	drop_order = [4,3,7,2,1,8]
	add_scheme = 'ordered_same_relu'
	add_order = [4,5,8]

	[train.dispatch]
		nb_gpus = 1
		platform = "slurm"
		exclude = """ai01,ai02,ai03,ai04,ai05,\
				   affogato12,affogato13,affogato14,\
				   adriatic02,adriatic03,adriatic04,adriatic05,adriatic06,\
			   	   lynx01,lynx02,lynx04,lynx05,lynx06,lynx07,cheetah01,lotus"""

[verify]
	debug = true
	eps = 0.01
	time = 600
	memory = '16G'
	[verify.verifiers]
		DNNV = ['neurify']
		# DNNV = ['eran_deeppoly','neurify','nnenum']
		# DNNF = ['default']

	[verify.dispatch]
		platform = "slurm"
		#reservation = "dx3yy_28"
		nb_cpus = 6
		nodes = ['cortado01','cortado02','cortado03','cortado04','cortado05','cortado06','cortado07','cortado08','cortado09']
		task_per_node = 7
