name = 'CIFAR'

[dnn]
	artifact = 'CIFAR10'
	onnx = './configs/networks/cifar_conv_big.onnx'
	r4v_config = './configs/networks/cifar_conv_big.toml'
	supported_layers= ['Conv', 'FC', 'Transpose', 'Flatten']
	start_layer = 0

[ca]
	strength = 3

	[ca.parameters]
		[ca.parameters.level]
			neu = 3
			conv = 5
			prop = 5

		[ca.parameters.range]
			neu = ['1/3', '1']
			conv = ['1/5', '1']
			prop = [0, 4]

[evolutionary]
	explore_iterations = 10
	refine_iterations = 2
	refine_arity = 2

	inflation_rate = 2
	deflation_rate = 0.5

	parameters = ['neu', 'conv']
	parameters_lower_bounds = {'conv'='1/5', 'neu'='1/3'}
	parameters_upper_bounds = {'conv'='125/3', 'neu'='24'}

[train]
	epochs = 10
	drop_scheme = 'random'
	add_scheme = 'last_same_relu'

	[train.dispatch]
		nb_cpus = 8
		nb_gpus = 1
		platform = "slurm"
		#partition = "gpu"
		#exclude = """cheetah01,cheetah02,cheetah03,cheetah04,cheetah05,ristretto01,sds01,sds02,lotus,adriatic01,adriatic02,adriatic03,adriatic04,adriatic05,adriatic06,jaguar01,jaguar02,jaguar03,jaguar04,jaguar05,jaguar06"""
		partition = "gnolim"
		exclude = """jinx01,jinx02,titanx01,titanx02,titanx03,titanx04,titanx05,serval01,cheetah05"""

[verify]
	debug = true
	#eps = 0.00784313725 #2/255
	eps = 0.00392156863 #1/255
	time = 600
	memory = '16G'
	setup_cmds = ['export MKL_SERVICE_FORCE_INTEL=1']

	[verify.verifiers]
		# DNNV = ['eran_deepzono']
		# DNNV = ['eran_deeppoly','neurify','nnenum']
		# DNNF = ['default']
		SwarmHost = ['nnenum']

	[verify.dispatch]
		platform = "slurm"
		nb_cpus = 6
		task_per_node = 8
		
		partition='main'
		nodes = ['cortado06','cortado07','cortado08','cortado09','cortado10']